### ISSUE TITLE
commit has error with unlinking temp files

### ISSUE THREAD

**Issue by hanselke** [gorillamania/AICodeBot#47]
aicodebot, version 0.12.2

`Do you want to use this commit message (type n to edit)? [Y/n]: y
Are you ready to commit the changes? [Y/n]: y
✅ 1 file(s) committed.
Traceback (most recent call last):
  File "/Users/hanselke/miniforge3/envs/devbot/bin/aicodebot", line 8, in <module>
    sys.exit(cli())
  File "/Users/hanselke/miniforge3/envs/devbot/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hanselke/miniforge3/envs/devbot/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/hanselke/miniforge3/envs/devbot/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hanselke/miniforge3/envs/devbot/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hanselke/miniforge3/envs/devbot/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/hanselke/miniforge3/envs/devbot/lib/python3.10/site-packages/aicodebot/cli.py", line 184, in commit
    Path.unlink(temp_file_name)
  File "/Users/hanselke/miniforge3/envs/devbot/lib/python3.10/pathlib.py", line 1206, in unlink
    self._accessor.unlink(self)
AttributeError: 'str' object has no attribute '_accessor'`

it commits fine. not really sure what you're doing with those temp files.

**Comment by gorillamania** [comment]
I thought I fixed all these. It's an issue with older versions of python. Curious - what version of python are you using?

Fixed with aicodebot 0.13.1
`pip install -U aicodebot` to upgrade

**Comment by hanselke** [comment]
Python 3.10.12

Yup, upgrade fixed it.
