### ISSUE TITLE
AttributeError: 'function' object has no attribute 'name' on fresh install python 3.10.12

### ISSUE THREAD

**Issue by gorillamania** [gorillamania/AICodeBot#74]
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aicodebot", line 5, in <module>
    from aicodebot.cli import cli
  File "/home/ubuntu/.local/lib/python3.10/site-packages/aicodebot/cli.py", line 38, in <module>
    cli.add_command(review)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1808, in add_command
    name = name or cmd.name
AttributeError: 'function' object has no attribute 'name'

**Comment by gorillamania** [comment]
Appears to be only on linux?
